### ISSUE TITLE
Adding version numbers or dates to the list

### ISSUE THREAD

**Issue by adbar** [scrapinghub/article-extraction-benchmark#23]
Hi, as time passes some tools evolve. Not all of them are under active development or maintenance, but results do change, see e.g. commit https://github.com/adbar/trafilatura/commit/e5ef7e0a8df14148bc965f6857537a229f6ac3dc on my benchmark.

It would be nice to provide the version numbers in the evaluation, or at least dates to indicate which version is referenced.

**Comment by lopuhin** [comment]
Good idea, thanks! Done in 22ef2c5e08ab0cd052a0fda72c5eac41e2134eb7
